---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: data-storage-delivery-deployment
spec:
  selector:
    matchLabels:
      app: data-storage-delivery
  replicas: 1
  template:
    metadata:
      labels:
        app: data-storage-delivery
    spec:
      containers:
      - name: data-storage-delivery
        image: lgsvl/data-marketplace-file-delivery:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: CHAIN_SERVICE_HOST
          value: "http://chaincode-rest-service:9090/"




